trainer: forces

dataset:
  - src: /checkpoint/electrocatalysis/relaxations/features/struct_to_energy_forces/train/200k/
  - src: /checkpoint/electrocatalysis/relaxations/features/struct_to_energy_forces/val/is_30000/

model:
  name: forcenet
  num_interactions: 5
  cutoff: 6
  basis: "sphallmul"
  ablation: None
  depth_mlp_edge: 2
  depth_mlp_node: 1
  act: "swish"
  decoder_act: "swish"
  feat: "full"
  hidden_channels: 128
  decoder_final_channels: 128
  max_n: 3

optim:
  batch_size: 8
  eval_batch_size: 12
  eval_every: -10000
  num_workers: 64
  lr_initial: 0.0005
  lr_schedule: fixed
  max_epochs: 15
  energy_coefficient: 0
  num_workers: 0

task:
  dataset: trajectory_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
  primary_metric: forces_mae
  labels:
    - potential energy
  grad_input: atomic forces
  tag_specific_weights:
    - 0.05
    - 1.0
    - 1.0
