trainer: forces

dataset:
  - src: /checkpoint/electrocatalysis/relaxations/features/struct_to_energy_forces/train/200k/
    normalize_labels: True
    target_mean: -0.7554450631141663
    target_std: 2.887317180633545
    grad_target_mean: 0.0
    grad_target_std: 2.887317180633545
  - src: /checkpoint/electrocatalysis/relaxations/features/struct_to_energy_forces/val/is_30000/

model:
  name: forcenet

optim:
  batch_size: 16
  eval_batch_size: 12
  eval_every: -10000
  num_workers: 64
  lr_initial: 0.0001
  lr_gamma: 0.1
  lr_milestones: # epochs at which lr_initial <- lr_initial * lr_gamma
    - 3
    - 5
    - 7
  warmup_epochs: 2
  warmup_factor: 0.2
  max_epochs: 15
  energy_coefficient: 0

task:
  dataset: trajectory_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
  primary_metric: forces_mae
  labels:
    - potential energy
  grad_input: atomic forces
  tag_specific_weights:
    - 0.05
    - 1.0
    - 1.0
