trainer: dist_forces

dataset:
  - src: /checkpoint/electrocatalysis/relaxations/features/struct_to_energy_forces/train/200k
    normalize_labels: True
    target_mean: -0.6545229554176331
    target_std: 3.066107988357544
    grad_target_mean: 0.0
    grad_target_std: 3.066107988357544
  - src: /checkpoint/electrocatalysis/relaxations/features/struct_to_energy_forces/val/is

logger: tensorboard

task:
  dataset: trajectory_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
  labels:
    - potential energy
  grad_input: atomic forces
  train_on_free_atoms: False
  eval_on_free_atoms: True
