trainer: forces

dataset:
  - src: data/data/2020_07_07_ocp_1k_original_fixed_correction/train/data.lmdb
    normalize_labels: True
    target_mean: -0.7879174947738647
    target_std: 2.895169973373413
    grad_target_mean: 0.0
    grad_target_std: 2.895169973373413
  - src: data/data/2020_07_07_ocp_1k_original_fixed_correction/val/data.lmdb

logger: tensorboard

task:
  dataset: trajectory_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
  labels:
    - potential energy
  grad_input: atomic forces
